services:
  - name: sharebuddy-api
    type: web
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: S3_REGION
        value: us-east-1
      - key: S3_ENDPOINT
        fromService:
          name: sharebuddy-minio
          type: web
          property: hostport
      - key: S3_ACCESS_KEY
        sync: false
      - key: S3_SECRET_KEY
        sync: false
      - key: S3_BUCKET
        value: sharebuddy
      - key: DATABASE_URL
        fromDatabase:
          name: sharebuddy-db
          property: connectionString

  - name: sharebuddy-minio
    type: web
    env: docker
    dockerfilePath: ./minio.Dockerfile
    plan: free
    envVars:
      - key: MINIO_ROOT_USER
        sync: false
      - key: MINIO_ROOT_PASSWORD
        sync: false
      - key: MINIO_BROWSER_REDIRECT_URL
        sync: false
      - key: MINIO_SERVER_URL
        sync: false
    disk:
      name: minio-data
      mountPath: /data
      sizeGB: 10
    healthCheckPath: /minio/health/live
    port: 9000 