services:
  - name: sharebuddy-api
    type: web
    env: node
    buildCommand: cd server && npm install && cd ../client && npm install && npm run build && cd ..
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: S3_REGION
        value: auto
      - key: S3_ENDPOINT
        sync: false
      - key: S3_ACCESS_KEY
        sync: false
      - key: S3_SECRET_KEY
        sync: false
      - key: S3_BUCKET
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: sharebuddy-db
          property: connectionString

  - name: sharebuddy-minio
    type: web
    env: docker
    dockerfilePath: ./minio.Dockerfile
    plan: free
    envVars:
      - key: MINIO_ROOT_USER
        sync: false
      - key: MINIO_ROOT_PASSWORD
        sync: false
      - key: MINIO_BROWSER_REDIRECT_URL
        sync: false
      - key: MINIO_SERVER_URL
        sync: false
    healthCheckPath: /minio/health/live 